### ISSUE TITLE
Is it possible to add: TLS_PSK_WITH_AES_128_GCM_SHA256 to the Cipher suite?

### ISSUE THREAD

**Issue by ahadcove** [nodertc/dtls#20]
Is it possible to add TLS_PSK_WITH_AES_128_GCM_SHA256 to the cipher suite?

---

* [RFC4279](https://tools.ietf.org/html/rfc4279) Pre-Shared Key Ciphersuites for Transport Layer Security (TLS)
* [RFC5487](https://tools.ietf.org/html/rfc5487) Pre-Shared Key Cipher Suites for TLS with SHA-256/384 and AES Galois Counter Mode
* https://tools.ietf.org/html/draft-ietf-tls-sharedkeys-02

**Comment by reklatsmasters** [comment]
Yes, of cource. I thought about ECDHE_PSK (#16) - modern secure cipher. However, i need some research of PSK key exchange brefore.

**Comment by ahadcove** [comment]
Oh awesome!
I would love to help, I just have to figure out where to start to learn about these things.
I actually need that Cipher to connect to Phillips Hue's Entertainment Bridge. They use DTLS apparently with that Cipher.
That's how I came across this cool project

**Comment by reklatsmasters** [comment]
Could you suggest any tools or something else to debug PSK? Should i generate special certificate type?

**Comment by ahadcove** [comment]
Hmm, the only thing that I know that uses it is Phillips Hue's Bridge Entertainment

**Comment by reklatsmasters** [comment]
@AhadCove i will add `TLS_PSK_WITH_AES_128_GCM_SHA256` in the next few weeks. I found the way to debug PSK key exchange.

**Comment by ahadcove** [comment]
This is awesome. Thank you for the update

**Comment by reklatsmasters** [comment]
@AhadCove Sorry, i changed my plans. I will not add new key exchange types in the near future. It’s hard to maintain by oneself. 

I suggest you use native bindings.
