### ISSUE TITLE
Specified custom port doesn't seem to work

### ISSUE THREAD

**Issue by Milannv** [nodertc/dtls#27]
Hi, I'm trying to bind the process to a specific port however, the port is ignored when creating a new socket.

**(Truncated) sample code**
```javascript
const dtls = require('@nodertc/dtls');
const dgram = require('dgram');
const udp = dgram.createSocket('udp4');

const socket = dtls.connect({
  socket: udp,
  remotePort: 4445,
  remoteAddress: '127.0.0.1',
});

udp.on('listening', () => {
  const address = udp.address();
  console.log(`UDP server listening at ${address.address}:${address.port}`);
});
```

Running the code above (code is truncated) outputs this in the console: ``` UDP server listening at 0.0.0.0:59102 ```. In other words, a random port is used. To verify, I used ``` $ netstat -plun``` and it shows a random port is used.

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 0.0.0.0:59102           0.0.0.0:*                           24098/node /var/www
```

Looking at the dgram documentation, the following is written:
[When address and port are not passed to socket.bind() the method will bind the socket to the "all interfaces" address on a random port (it does the right thing for both udp4 and udp6 sockets)"](https://nodejs.org/dist/latest-v8.x/docs/api/dgram.html#dgram_dgram_createsocket_options_callback)

This made me try the following, binding a port on the udp object like so

```
udp.bind(41234);
```

Doing so generates the following error:

```
0|index  | AssertionError [ERR_ASSERTION]: Forbidden transition from 5633 to 5633
0|index  |     at Protocol12ReaderClient.next (/var/www/ws/node_modules/@nodertc/dtls/src/node_modules/fsm/protocol.js:175:7)
0|index  |     at Protocol12ReaderClient._write (/var/www/ws/node_modules/@nodertc/dtls/src/node_modules/fsm/protocol.js:208:12)
0|index  |     at doWrite (/var/www/ws/node_modules/readable-stream/lib/_stream_writable.js:429:139)
0|index  |     at writeOrBuffer (/var/www/ws/node_modules/readable-stream/lib/_stream_writable.js:418:5)
0|index  |     at Protocol12ReaderClient.Writable.write (/var/www/ws/node_modules/readable-stream/lib/_stream_writable.js:327:11)
0|index  |     at Defragmentation.ondata (/var/www/ws/node_modules/readable-stream/lib/_stream_readable.js:635:20)
0|index  |     at Defragmentation.emit (events.js:182:13)
0|index  |     at Defragmentation.EventEmitter.emit (domain.js:442:20)
0|index  |     at addChunk (/var/www/ws/node_modules/readable-stream/lib/_stream_readable.js:301:12)
0|index  |     at readableAddChunk (/var/www/ws/node_modules/readable-stream/lib/_stream_readable.js:283:11)
```

I had a look at the ```example.js``` file you provided, but that doesn't seem to work for me as well.

```javascript
const socket = dtls.connect({
  type: 'udp4',
  remotePort: 4444,
  remoteAddress: '127.0.0.1',
});
```

Running this piece of code also assigns a random port. 

Node version: v10.13.0

OS Version:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by reklatsmasters** [comment]
Hello, @Milannv. 

You may bind a custom port using `port` option:

```js
const dtls = require('@nodertc/dtls');
const dgram = require('dgram');
const udp = dgram.createSocket('udp4');

const socket = dtls.connect({
  socket: udp,
  port: 5555,
  remotePort: 4444,
  remoteAddress: '127.0.0.1',
});
```

It means that you want to listen on port `5555` and want to receive data from port `4444`. Also you may specify a custom message filter if you receive data from many interfaces. See [`unicast`](https://www.npmjs.com/package/unicast#api) api.

**Comment by Milannv** [comment]
Hi @reklatsmasters,

Thanks for your quick reply. I ran your snippet above, but it still picks a random port for me. 

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
udp        0      0 0.0.0.0:40477           0.0.0.0:*                           25254/node /var/www 
```

EDIT:
I tried your unicast API suggestion, that one spawns a process listening to the specified port.

**Comment by reklatsmasters** [comment]
~~It's a bug in unicast.~~ Try this:

```js
const dtls = require('@nodertc/dtls');

const socket = dtls.connect({
  type: 'udp4',
  port: 5555,
  remotePort: 4444,
  remoteAddress: '127.0.0.1',
});
```
Unicast bind to a custom port only self-created sockets. ~~I will fix it.~~

https://github.com/reklatsmasters/unicast/blob/fe83eb884bcd8687e50a4b5163a5af584d32444b/lib/create-socket.js#L16-L30

**Comment by reklatsmasters** [comment]
@Milannv Stop. If you provide a custom / external socket, you should bind your socket myself. Right answer is:

```js
const dtls = require('@nodertc/dtls');
const dgram = require('dgram');

const udp = dgram.createSocket('udp4');

udp.bind(5555);

const socket = dtls.connect({
  socket: udp,
  remotePort: 4445,
  remoteAddress: '127.0.0.1',
});

udp.on('listening', () => {
  const address = udp.address();
  console.log(`UDP server listening at ${address.address}:${address.port}`);
});
```
