### ISSUE TITLE
Module not found: Error: Can't resolve 'lib/socket'

### ISSUE THREAD

**Issue by gidhin** [nodertc/dtls#31]
It not woking for. Im using in the ionic 3 app. Please give me the solution.

error : Module not found: Error: Can't resolve 'dgram'

Thank you.

**Comment by reklatsmasters** [comment]
@gidhin Please, provide some info:

* nodejs version
* how do you install and use this module?

**Comment by gidhin** [comment]
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 6.5.0 

local packages:

    @ionic/app-scripts : 3.2.1
    Cordova Platforms  : android 6.3.0 ios 4.3.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v8.10.0
    npm               : 5.6.0 
    OS                : macOS High Sierra
    Xcode             : Xcode 10.1 Build version 10B61 

Environment Variables:

    ANDROID_HOME : /Users/#####/Library/Android/sdk

Misc:

    backend : pro

**Comment by reklatsmasters** [comment]
Do you want to run this module on mobile device? It’s a mistake. This library should work on a server.

**Comment by gidhin** [comment]
Okay Thank you so much. Can you tell me how can i do it from mobile side.
Im using Ionic app. I need to DTLS Handshaking for my ionic app.

Thanks and Regards,
Gidhin S

**Comment by reklatsmasters** [comment]
@gidhin You should get access to udp sockets as says error message “Can't resolve 'dgram' “. However, it’s not tested on mobile devices.

**Comment by gidhin** [comment]
Thank you for your response. Is there any other options for doing it from
mobile devices ?

Thanks and Regards,
Gidhin S

**Comment by reklatsmasters** [comment]
@gidhin No. DTLS communicates over UDP. If you don’t have access to the UDP socket, then you don’t have DTLS.

**Comment by gidhin** [comment]
Thank you for your response.
so no other option for DTLS commissioning from mobile app and i want to do
thread operation.

Thanks and Regards,
Gidhin S
