### ISSUE TITLE
TLS_RSA_WITH_AES_128_CBC_SHA (x002f)  cipher suite

### ISSUE THREAD

**Issue by prasanth1983** [nodertc/dtls#35]
Please add support for the cipher suite TLS_RSA_WITH_AES_128_CBC_SHA (x002f) .. if yes please do let me know the steps to add

**Comment by reklatsmasters** [comment]
CBC cipher is not a part of AEAD. Also, ciphers with SHA1 deprecated.
Please, use modern AEAD ciphers.

пт, 10 мая 2019 г., 18:14 prasanth1983 <notifications@github.com>:

**Comment by prasanth1983** [comment]
My server only accepts this cipher suite..  I have no other option ..
please suggest

**Comment by reklatsmasters** [comment]
Sorry, but I have no plans to implement non-AEAD algorithms.

пт, 10 мая 2019 г., 19:02 prasanth1983 <notifications@github.com>:
